"""Security module for Thirstys Waterfall - Advanced Security Features"""

from .hardware_root_of_trust import (
    HardwareRootOfTrust,
    TPMInterface,
    SecureEnclaveInterface,
    HSMInterface,
    HardwareType,
    AttestationStatus,
    HardwareInterface
)
from .privacy_risk_engine import PrivacyRiskEngine, RiskLevel
from .microvm_isolation import MicroVMIsolationManager, MicroVMInstance
from .mfa_auth import (
    MFAAuthenticator,
    AuthContext,
    AuthMethod,
    AuthLevel,
    TOTPProvider,
    FIDO2Provider,
    PasskeyProvider,
    CertificateProvider,
    BiometricProvider,
    BiometricType,
)
from .dos_trap import (
    DOSTrapMode,
    CompromiseDetector,
    CompromiseEvent,
    CompromiseType,
    ThreatLevel,
    ResponseAction,
    SanitizationMode,
    SecretWiper,
    HardwareKeyDestroyer,
    InterfaceDisabler,
    MemorySanitizer,
    DiskSanitizer,
    create_dos_trap,
)

__all__ = [
    'HardwareRootOfTrust',
    'TPMInterface',
    'SecureEnclaveInterface',
    'HSMInterface',
    'HardwareType',
    'AttestationStatus',
    'HardwareInterface',
    'PrivacyRiskEngine',
    'RiskLevel',
    'MicroVMIsolationManager',
    'MicroVMInstance',
    'MFAAuthenticator',
    'AuthContext',
    'AuthMethod',
    'AuthLevel',
    'TOTPProvider',
    'FIDO2Provider',
    'PasskeyProvider',
    'CertificateProvider',
    'BiometricProvider',
    'BiometricType',
    'DOSTrapMode',
    'CompromiseDetector',
    'CompromiseEvent',
    'CompromiseType',
    'ThreatLevel',
    'ResponseAction',
    'SanitizationMode',
    'SecretWiper',
    'HardwareKeyDestroyer',
    'InterfaceDisabler',
    'MemorySanitizer',
    'DiskSanitizer',
    'create_dos_trap',
]
